# Generated by Django 2.0.3 on 2018-04-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=50, verbose_name='电脑品牌')),
                ('cpu_num', models.IntegerField(default=0, verbose_name='cpu核数')),
            ],
            options={
                'db_table': 'django3_computer',
            },
        ),
    ]
