# Generated by Django 2.0.3 on 2018-04-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='memory',
            field=models.IntegerField(default=8, verbose_name='内存(G)'),
        ),
    ]
