# Generated by Django 2.0.3 on 2018-04-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='photo',
            field=models.ImageField(default='default/none.jpg', upload_to='photo'),
        ),
    ]
