# Generated by Django 2.0.3 on 2018-04-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(default='default/django.jpeg', upload_to='photo'),
        ),
    ]
