# Generated by Django 2.0.3 on 2018-04-08 07:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180403_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='uploadfile',
            field=models.FileField(default='', storage=django.core.files.storage.FileSystemStorage(location='/Users/hanqunfeng/python_workspace/FILE/'), upload_to='file'),
        ),
    ]
