# Generated by Django 2.0.3 on 2018-04-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityCard',
            fields=[
                ('cardId', models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号')),
                ('address', models.CharField(blank=True, max_length=20, null=True, verbose_name='地址')),
                ('issuing_organ', models.CharField(blank=True, max_length=20, null=True, verbose_name='发证机关')),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='有效期截止')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.User')),
            ],
            options={
                'db_table': 'sys_user_idcard',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码'),
        ),
    ]
