# Generated by Django 2.0.3 on 2018-04-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180408_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carNum', models.CharField(max_length=10)),
                ('carColor', models.IntegerField(choices=[(1, 'red'), (2, 'black'), (3, 'blue')])),
                ('user', models.ManyToManyField(to='myapp.User')),
            ],
        ),
    ]
