# Generated by Django 2.0.3 on 2018-04-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180411_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='车辆价格(万元)'),
        ),
    ]
