# Generated by Django 2.0.3 on 2018-04-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(db_column='book_name', max_length=50, verbose_name='书名')),
                ('bookpapers', models.IntegerField(db_column='book_papers', default=0, verbose_name='页数')),
            ],
            options={
                'db_table': 'django2_book',
            },
        ),
    ]
