# Generated by Django 2.0.3 on 2018-04-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(db_column='book_author', db_index=True, default='', max_length=20, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookname',
            field=models.CharField(db_column='book_name', max_length=50, unique=True, verbose_name='书名'),
        ),
    ]
